# Generated by Django 3.0.3 on 2020-02-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallurlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortUrls',
            new_name='short_urls',
        ),
    ]
